version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-codebot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-codebotpass}
      POSTGRES_DB: ${POSTGRES_DB:-codebot_dev}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      timeout: 5s

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file: .env
    volumes:
      - ./:/app
    command: >
      sh -c "
        alembic upgrade head &&
        python scripts/seed_data.py &&
        uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT:-8000} --reload
      "

volumes:
  db_data:
